server:
  port: 9002

spring:
  application:
    name: springboot-model-client-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: fastgo123
    url: jdbc:mysql://127.0.0.1:3306/db_spb_demo?Unicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:6666/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url-path: /swagger-ui.html


logging:
  level:
    com.idea.spbmodeldemo.dao.mapper: debug

mybatis:
  type-aliases-package: com.spbmodeldemo.dao.entity.po
  mapper-locations: classpath:mapper/*.xml
